# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'password_dialog_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RecoveryPassword(object):
    def setupUi(self, RecoveryPassword):
        RecoveryPassword.setObjectName("RecoveryPassword")
        RecoveryPassword.resize(407, 144)
        RecoveryPassword.setMinimumSize(QtCore.QSize(407, 144))
        RecoveryPassword.setMaximumSize(QtCore.QSize(16777215, 144))
        RecoveryPassword.setStyleSheet("QWidget#RecoveryPassword {background-color: rgb(0, 51, 102);}\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(RecoveryPassword)
        self.gridLayout.setObjectName("gridLayout")
        self.input_repeat_password = QtWidgets.QLineEdit(RecoveryPassword)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(14)
        self.input_repeat_password.setFont(font)
        self.input_repeat_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_repeat_password.setObjectName("input_repeat_password")
        self.gridLayout.addWidget(self.input_repeat_password, 1, 1, 1, 1)
        self.message_label = QtWidgets.QLabel(RecoveryPassword)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(14)
        self.message_label.setFont(font)
        self.message_label.setStyleSheet("color: rgb(255, 0, 0);")
        self.message_label.setText("")
        self.message_label.setObjectName("message_label")
        self.gridLayout.addWidget(self.message_label, 3, 0, 1, 2)
        self.btn_enter = QtWidgets.QPushButton(RecoveryPassword)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(14)
        self.btn_enter.setFont(font)
        self.btn_enter.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.btn_enter.setObjectName("btn_enter")
        self.gridLayout.addWidget(self.btn_enter, 2, 0, 1, 2)
        self.label = QtWidgets.QLabel(RecoveryPassword)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 242, 242);")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(RecoveryPassword)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 242, 242);")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.input_password = QtWidgets.QLineEdit(RecoveryPassword)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(14)
        self.input_password.setFont(font)
        self.input_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_password.setObjectName("input_password")
        self.gridLayout.addWidget(self.input_password, 0, 1, 1, 1)

        self.retranslateUi(RecoveryPassword)
        QtCore.QMetaObject.connectSlotsByName(RecoveryPassword)

    def retranslateUi(self, RecoveryPassword):
        _translate = QtCore.QCoreApplication.translate
        RecoveryPassword.setWindowTitle(_translate("RecoveryPassword", "Recovery password"))
        self.btn_enter.setText(_translate("RecoveryPassword", "Подтвердить изменения"))
        self.label.setToolTip(_translate("RecoveryPassword", "<html><head/><body><p><span style=\" color:#0000ff;\">Требования к паролю:</span></p><p><span style=\" color:#0000ff;\">- Не менее 8 символов</span></p><p><span style=\" color:#0000ff;\">- Должен содержать буквы разных регистров</span></p><p><span style=\" color:#0000ff;\">- В пароле должна быть хотя бы одна цифра</span></p></body></html>"))
        self.label.setText(_translate("RecoveryPassword", "Новый пароль"))
        self.label_2.setText(_translate("RecoveryPassword", "Повторите пароль"))
        self.input_password.setToolTip(_translate("RecoveryPassword", "<html><head/><body><p>Нажмите F1, чтобы увидеть пароль</p><p>Нажмите F2, чтобы сгенерировать случайный пароль</p></body></html>"))
