# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'read_message_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_message_information_form(object):
    def setupUi(self, message_information_form):
        message_information_form.setObjectName("message_information_form")
        message_information_form.resize(732, 328)
        message_information_form.setStyleSheet("QWidget#message_information_form {background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:0, stop:1 rgba(0, 0, 128, 255));;}\n"
"QWidget#message_information_form {border: 1px solid orange;}")
        self.gridLayout = QtWidgets.QGridLayout(message_information_form)
        self.gridLayout.setObjectName("gridLayout")
        self.message = QtWidgets.QTextBrowser(message_information_form)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.message.setFont(font)
        self.message.setObjectName("message")
        self.gridLayout.addWidget(self.message, 0, 0, 1, 1)

        self.retranslateUi(message_information_form)
        QtCore.QMetaObject.connectSlotsByName(message_information_form)

    def retranslateUi(self, message_information_form):
        _translate = QtCore.QCoreApplication.translate
        message_information_form.setWindowTitle(_translate("message_information_form", "Form"))
